# Generated by Django 4.1.3 on 2023-12-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="名前")),
                ("image", models.ImageField(upload_to="image", verbose_name="画像")),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="商品名")),
                ("content", models.TextField(verbose_name="商品説明")),
                ("image", models.ImageField(upload_to="image", verbose_name="商品説明")),
                ("price", models.PositiveIntegerField(verbose_name="値段")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="投稿日時"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.category",
                        verbose_name="カテゴリー",
                    ),
                ),
            ],
        ),
    ]
