# Generated by Django 4.1.3 on 2023-12-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_order_orderitem_remove_cartitem_cart_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
